import hashlib
import re
from datetime import datetime, timezone
from pathlib import Path

import yaml

from llm_wiki import __version__, __git_hash__


def compute_sha(path: Path) -> str:
    """Return first 8 hex chars of SHA-256 of file contents."""
    h = hashlib.sha256(path.read_bytes())
    return h.hexdigest()[:8]


def inject_footer(
    content: str,
    version: str,
    git_hash: str,
    template: str,
    date: str,
) -> str:
    """Append traceability footer to markdown content."""
    footer = (
        f"\n\n---\n"
        f"*Generated by llm-wiki-tools v{version} "
        f"(commit {git_hash}) · {date} · template: {template}*\n"
    )
    return content.rstrip() + footer


def write_tmp(
    wiki_dir: Path,
    source_path: Path,
    backend_name: str,
    markdown_body: str,
    ingest_command: str,
) -> tuple[Path, dict]:
    """Write converted markdown to wiki/.tmp/ with frontmatter.

    Returns (tmp_path, summary_dict).
    """
    tmp_dir = wiki_dir / ".tmp"
    tmp_dir.mkdir(parents=True, exist_ok=True)

    date_str = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    safe_name = re.sub(r"[^\w.\-]", "_", source_path.name)
    out_path = tmp_dir / f"{date_str}_{safe_name}.md"

    source_sha = compute_sha(source_path)
    ingested_at = datetime.now(timezone.utc).isoformat()

    meta = {
        "source": str(source_path),
        "source-sha": source_sha,
        "source-type": source_path.suffix.lstrip(".").lower(),
        "ingest-command": ingest_command,
        "ingest-backend": backend_name,
        "lwt-version": __version__,
        "lwt-git-hash": __git_hash__,
        "ingested-at": ingested_at,
    }

    frontmatter = yaml.dump(meta, default_flow_style=False, allow_unicode=True)
    full_content = f"---\n{frontmatter}---\n\n{markdown_body}"
    out_path.write_text(full_content, encoding="utf-8")

    lines = len(markdown_body.splitlines())
    sections = len(re.findall(r"^#{2,3} ", markdown_body, re.MULTILINE))

    return out_path, {
        "path": out_path,
        "lines": lines,
        "sections": sections,
        "backend": backend_name,
        "source_sha": source_sha,
    }
